### ISSUE TITLE
From html files?

### ISSUE THREAD

**Issue by albertosantini** [jediq/grunt-lunr-index-generator#1]
What about generating the index also from the html files?

**Comment by jediq-ricky** [comment]
Hi Alberto

Thanks for the suggestion.

I haven't yet generated the index from HTML as the parsing of the markdown file is very rudimentary, parsing and extracting header tags from html would be a lot more involved.

**Comment by albertosantini** [comment]
Agreed.

I review my use case tomorrow and I report you a feedback, closing the issue or suggesting further steps.

**Comment by albertosantini** [comment]
Thanks for html support.

I tested [Added support for html file sources](https://github.com/jediq/grunt-lunr-index-generator/commit/17bb273889b999a27fbf63ae8975314366326e98) and it works nice.

My use case is generating docs from markdown embedded in js with docco and creating a full text search index with lunr.

```
        lunr_index_generator: {
            web_docs: {
                src: ["web_docs/*.html"],
                dest: "web_docs/search_data.json"
            }
        }
```

(Don't forget to push a new release to npm) :)

**Comment by jediq-ricky** [comment]
Thanks Alberto, version 0.1.3 is now available in npm.

**Comment by julkue** [comment]
I don't think the HTML index generation was implemented correctly. I have a 39 KB HTML file and it will generate a 255 KB lunr.json _compressed_. Uncompressed it's 3906 KB :octopus:
An HTML `<ul>` menu with a depth of e.g. 10 sub-menus will cause an nearby endless tree generated...
